### ISSUE TITLE
error when loading pretrained ResNet-50 model

### ISSUE THREAD

**Issue by scut-salmon** [layumi/Person_reID_baseline_pytorch#37]
Hi,
I download the pretrainded model offered by the author from [Googledrive](https://drive.google.com/file/d/1__x0qNJ3T654wTghmuRjydn42NsAZW_M/view)

But it went error as follow
RuntimeError: Error(s) in loading state_dict for ft_net:
        Missing key(s) in state_dict: "model.fc.weight", "model.fc.bias", "classifier.add_block.0.weight", "classifier.add_block.0.bias", "classifier.add_block.1.weight", "classifier.add_block.1.bias", "classifier.add_block.1.running_mean", "classifier.add_block.1.running_var", "classifier.classifier.0.weight", "classifier.classifier.0.bias". 
        Unexpected key(s) in state_dict: "model.fc.0.weight", "model.fc.0.bias", "model.fc.1.weight", "model.fc.1.bias", "model.fc.1.running_mean", "model.fc.1.running_var", "classifier.0.weight", "classifier.0.bias". 

How can I solve this problem? Any suggestion would be appreciable.
Thanks,
Zhang

**Comment by layumi** [comment]
Sorry. It is my mistake. 
The trained model is for the old version.
I have updated the code style of the model structure. So it can not find the classifier.

Could you train the model and test it? It will be fine.

**Comment by scut-salmon** [comment]
@layumi Hi, how can I get your updated code or updated trained model? I just redownload the whole project, and make a soft link of "model" and dataset. 
I use the following command:
python test.py --gpu_ids 1  --name ft_ResNet50 --test_dir Market-1501-v15.09.15/pytorch/ --which_epoch last
However, it's still not work, showing the same error as before.

**Comment by liuhengli** [comment]
@layumi Hi you have update new trained model I also have this error
